version: '3.8'

services:
  jira-unified-web:
    build: .
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    volumes:
      - .:/app
    working_dir: /app
    command: streamlit run unified_app.py --server.port=8501 --server.address=0.0.0.0
    restart: unless-stopped
    container_name: jira-unified-web
